# -*- coding: utf-8 -*-
"""
Created on Wed Aug  6 13:35:18 2025

@author: Tania

Se adiciona la columna Category para luego ser utilizada en la generación de descripcion por prompt
"""

import numpy as np
import pandas as pd
import random
from datetime import datetime, timedelta

# Set seed for reproducibility
np.random.seed(42)
random.seed(42)

# Cargar csv de base de datos fake de productos
csv_path = r"data_amazon/prod-elect-relog-roup-bols_fake.csv"
prod_df = pd.read_csv(csv_path, sep=";")

# Modalidades for Pareto distribution
type_modalidade = ['Postal', 'Expressa']

# Regime for Pareto distribution
type_regime = ['PRC - Integral - PF', 'Nao PRC']

# Pareto preferences
type_modalidade_weights = np.array([0.4, 0.6])
type_regime_weights = np.array([0.7, 0.3])

# Inicia con una fecha base
start_datetime = datetime(2025, 8, 1, 8, 0, 0)
current_datetime = start_datetime

# Mantiene todos los registros del CSV original
orders = []
for _, row in prod_df.iterrows():
    
    # Date and hour must be sequencial for the registers
    data_horario_registro_DIR = current_datetime
    current_datetime += timedelta(minutes=5)  # cada registro +5 min
    
    # Modalidade must be only two options: "Postal" or "Expressa"
    modalidade = np.random.choice(type_modalidade, p=type_modalidade_weights)
    
    # Situacao must: "Registrada"
    situacao = "Registrada"
    
    # Peso bruto (Kg) ≤ 50 kg
    peso_bruto_kg = round(np.random.uniform(0.5, 50), 2)
    
    # Volumes: 80% =1, 19%=2-5, 1%=>5
    r = np.random.rand()
    if r < 0.8:
        volumes_remessa = 1
    elif r < 0.99:
        volumes_remessa = np.random.randint(2, 6)
    else:
        volumes_remessa = np.random.randint(6, 101)
        
    # Tasa de cambio must be between 5.42 and 5.6
    tasa_cambio = round(np.random.uniform(5.42, 5.6), 2)
    
    # Calcula la media de MinPrice y MaxPrice
    media_precio = (row["MinPrice"] + row["MaxPrice"]) / 2
    
    # Valor total remessa must must be generated by LLM prompt, with reference on the values min_price and max_price
    valor_total_remessa = round(media_precio, 2)
    
    # Valor Frete fake value must not exceed 200 dollars
    valor_frete = round(np.random.uniform(0, 200), 2)
    
    # Valor tributável: 37% si <50 USD, 77% si ≥50 USD
    base = valor_total_remessa + valor_frete
    if valor_total_remessa < 50:
        valor_tributavel = round(base * 0.37, 2)
    else:
        valor_tributavel = round(base * 0.77, 2)

    # Pais remetente
    shipping_country = row['ShipCountry']
    
    # Descricao must be generated by LLM prompt based on row description
    descricao = row['Description']
    
    # Number of items of one type of product must be equal to volumes_remessa
    qtde_merc = volumes_remessa
    
    # must be in the format "DEZ UNIDADES" based on qtde_merc
    ume_merc = f"{qtde_merc} UNIDADES"
    
    # Total weight of items of one type of product must be between 0.5 to 50 kg
    peso_kg_merc = round(np.random.uniform(0.5, 50), 2)
    
    # Total value of items of one type of product = valor_total_remessa
    valor_merc = valor_total_remessa
    
    # Currency
    moeda_merc = "REALES"
    
    # Regime de tributacao must be "PRC - Integral - PF" or "Nao PRC"
    regime_tributo = np.random.choice(type_regime, p=type_regime_weights)
    
    # NCM - SH
    ncm_sh_merc = "39252000"
    
    # Valor provisionado II: 20% si <50 USD, 60% si ≥50
    if valor_total_remessa < 50:
        valor_prov_ii = round(base * 0.20, 2)
    else:
        valor_prov_ii = round(base * 0.60, 2)
        
    # Valor provisionado ICMS = 17%
    valor_prov_icms = round(base * 0.17, 2)
    
    # Agregamos la categoría original
    categoria = row['Category']

    orders.append([
        data_horario_registro_DIR, modalidade, situacao, peso_bruto_kg, volumes_remessa, tasa_cambio, valor_total_remessa,
        valor_frete, valor_tributavel, shipping_country, descricao, qtde_merc, ume_merc, peso_kg_merc, valor_merc,
        moeda_merc, regime_tributo, ncm_sh_merc, valor_prov_ii, valor_prov_icms, categoria
    ])

# Create DataFrame
df = pd.DataFrame(orders, columns=[
    'Data_horario_registro_DIR', 'Modalidade', 'Situacao', 'Peso_bruto_kg', 'Volumes_remessa', 'Tasa_cambio', 'Valor_total_remessa',
    'Valor_frete', 'Valor_tributavel', 'Pais_remetente', 'Descricao', 'Quantidade_mercadoria', 'UME_mercadoria', 'Peso_kg_mercadoria', 'Valor_mercadoria',
    'Moeda_mercadoria', 'Regime_tributario', 'NCM_SH_mercadoria', 'Valor_provisionado_II', 'Valor_provisionado_ICMS', 'Category'
])

# Save to CSV
output_path = r"data_amazon/prod-elect-relog-roup-bols_fake_sem_desc_val.csv"
df.to_csv(output_path, index=False, sep=';')
print("Archivo guardado exitosamente en:", output_path)
print(df.head())

